extra_fn_clean_exts:
    - type: regex
      pattern: '_\w*_S\d+_L\d{3}_R\d_\d{3}'
    - '.LibraryComplexity'

top_modules:
- 'fastqc'
- 'picard'

picard_config:
    general_stats_target_coverage:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30
        - 40
        - 50
        - 60
        - 70
        - 80
        - 90
        - 100

table_columns_visible:
    FastQC:
        percent_duplicates: False
        percent_gc: False
        avg_sequence_length: False
        percent_fails: False
        total_sequences: False
